// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need Neon's direct, unpooled connection — PgBouncer's
    // transaction-mode pooling (what DATABASE_URL points at) doesn't
    // reliably support the session-level operations `migrate deploy` needs,
    // and hangs rather than failing fast. Runtime queries still use the
    // pooled DATABASE_URL via the adapter in lib/db.ts.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
